# Generated by Django 5.2.7 on 2025-11-16 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cours_coursparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('planifie', 'planifié'), ('effectue', 'effectué'), ('annule', 'annulé')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coursparticipation',
            options={'ordering': ['-date_inscription']},
        ),
        migrations.AlterUniqueTogether(
            name='coursparticipation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cours',
            name='capacite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='coursparticipation',
            constraint=models.UniqueConstraint(fields=('user', 'cours'), name='unique_user_cours'),
        ),
        migrations.AddField(
            model_name='seance',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coach'),
        ),
        migrations.AddField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cours'),
        ),
    ]
