# Generated by Django 5.2.7 on 2025-11-16 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coach_seance_alter_coursparticipation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coach')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cours')),
            ],
            options={
                'verbose_name': 'Coach du cours',
                'verbose_name_plural': 'Coachs des cours',
                'unique_together': {('coach', 'cours')},
            },
        ),
    ]
