# Generated by Django 5.2.7 on 2025-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_amount_subscription_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='start_shift_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(choices=[('planifie', 'planifié'), ('effectue', 'effectué'), ('annule', 'annulé')], default='planifie', max_length=20),
        ),
    ]
