# Generated by Django 5.2.7 on 2025-11-22 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_seance_clients_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='clientcoachselection',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coach'),
        ),
        migrations.AlterField(
            model_name='coachcours',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coach'),
        ),
        migrations.AlterField(
            model_name='review',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coach'),
        ),
        migrations.AlterField(
            model_name='review',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'cours', 'coach', 'month')},
        ),
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('material', models.IntegerField(null=True)),
                ('equipment', models.IntegerField(null=True)),
                ('salle', models.IntegerField(null=True)),
                ('ambiance', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
