# Generated by Django 5.2.7 on 2025-11-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVideoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_videos', to='api.cours')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
