# Generated by Django 5.2.7 on 2025-11-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_aivideocache_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aivideocache',
            name='videos',
            field=models.JSONField(default=list),
        ),
    ]
